bremersee:
  access:
    application:
      authorities:
      - "ROLE_EUREKA"
      ip-addresses:
        - "127.0.0.1"
        - "::1"
    actuator:
      authorities:
      - "ROLE_ACTUATOR"
      ip-addresses:
      - "127.0.0.1"
      - "::1"
    users:
      - name: eureka
        password: secret4EUREKA
        authorities:
        - "ROLE_EUREKA"
      - name: actuator
        password: secret4ACTUATOR
        authorities:
        - "ROLE_ACTUATOR"

eureka:
  instance:
    hostname: ${HOST_NAME:localhost}
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

logging:
  level:
    ROOT: ${LOG_LEVEL_ROOT:INFO}
    org.springframework: ${LOG_LEVEL_SPRING:INFO}
    org.bremersee: ${LOG_LEVEL_BREMERSEE:DEBUG}

management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: ${SERVER_PORT:8761}
  servlet:
    context-path: ${CONTEXT_PATH:/}
  use-forward-headers: ${USE_FORWARD_HEADERS:true}
  tomcat:
    remote-ip-header: x-forwarded-for
    protocol-header: x-forwarded-proto
    port-header: x-forwarded-port

---

spring:
  profiles: logfiles

logging:
  path: ${LOG_PATH:/var/log/eureka}
  file:
    max-history: ${LOG_MAX_HISTORY:25}

server:
  tomcat:
    accesslog:
      enabled: ${ACCESS_LOG_ENABLED:true}
      directory: ${LOG_PATH:/var/log/eureka}
