bremersee:
  auth:
    resource-server: other
    eureka:
      username: ${EUREKA_USERNAME:eureka}
      password: ${EUREKA_PASSWORD:eureka}
      role: ${EUREKA_ROLE:ROLE_EUREKA}
    role-definitions:
      admin:
        - "ROLE_ADMIN"
        - "ROLE_EUREKA_ADMIN"
  cors:
    enable: true
    allow-all: true
  actuator:
    auth:
      enable: other
      enable-cors: true
  exception-mapping:
    api-paths:
      - /eureka/**
    default-exception-mapping-config:
      include-stack-trace: true
      include-cause: true
      include-application-name: true
      include-exception-class-name: true
      include-handler: true
      include-path: true
  redis:
    embedded: true

spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false

eureka:
  server:
    enable-self-preservation: ${ENABLE_SELF_PRESERVATION:true}
    eviction-interval-timer-in-ms: ${EVICTION_INTERVAL_TIMER:1000}
  instance:
    hostname: ${HOST_NAME:localhost}
    prefer-ip-address: ${PREFER_IP_ADDRESS:true}
    instance-id: ${spring.application.name}:${HOSTNAME:${random.value}}
  client:
    register-with-eureka: ${REGISTER_WITH_EUREKA:false}
    fetch-registry: ${FETCH_REGISTRY:false}
    service-url:
      defaultZone: ${DEFAULT_ZONE:http://${eureka.instance.hostname}:${server.port}/eureka/}

management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-headers: "*"
        allowed-methods: "*"
        allowed-origins: "*"
  endpoint:
    health:
      show-details: when_authorized

server:
  port: ${SERVER_PORT:8761}
  servlet:
    context-path: ${CONTEXT_PATH:/}
  tomcat:
    accesslog:
      enabled: false

logging:
  level:
    ROOT: info
    com.netflix.eureka.registry: warn
    com.netflix.discovery.shared.resolver: warn
    org.springframework.cloud.configclient: warn

---

spring:
  profiles: in-memory

bremersee:
  auth:
    in-memory-users:
      - name: "admin"
        password: "admin"
        authorities:
          - "ROLE_USER"
          - "ROLE_ADMIN"
      - name: "actuator"
        password: "actuator"
        authorities:
          - "ROLE_ACTUATOR"
          - "ROLE_ACTUATOR_ADMIN"
      - name: "user"
        password: "user"
        authorities:
          - "ROLE_USER"
